# SupertropicalPy: Complete Tutorial

A comprehensive guide to **supertropical algebra** in Python, covering elements, operations, matrices, and linear systems.

This tutorial combines all fundamental concepts in one place. You can also view individual sections:
- [Part 1: Elements & Operations](01_supertropical_elements.ipynb)
- [Part 2: Ghost Surpasses](02_ghost_surpasses.ipynb)
- [Part 3: Matrices](03_matrices.ipynb)
- [Part 4: Linear Systems](04_linear_systems.ipynb)

---

# 1. Supertropical Algebra: Elements & Operations

This section demonstrates **supertropical elements** and basic operations.

**Theory reference**: See `theory.rst` Section 1.1-1.3

## Setup

In [1]:
# Install package (for Google Colab)
!pip install -q SupertropicalPy

In [2]:
# import package
import supertropical as suptrop

## 1.1 Creating Elements

**Theory**: Extended semiring tropical $T = \mathbb{R} \cup \{-\infty\} \cup \mathbb{R}^\nu$

- **Tangible elements**: Regular real numbers
- **Ghost elements**: Marked with $\nu$ superscript

In [3]:
# Tangible elements
a = suptrop.Element(5)
b = suptrop.Element(3)

# Ghost elements
c = suptrop.Element(5, is_ghost=True)
d = suptrop.Element(2, is_ghost=True)

print("📌 Tangible Elements:")
print(f"   a = {a}")
print(f"   b = {b}")
print()
print("👻 Ghost Elements:")
print(f"   c = {c}")
print(f"   d = {d}")

📌 Tangible Elements:
   a = 5.0
   b = 3.0

👻 Ghost Elements:
   c = 5.0ν
   d = 2.0ν


## 1.2 Addition ($\oplus$)

**Axiom 1.1 rules**:
1. $-\infty \oplus x = x$ (neutral element)
2. $x \oplus y = \max(x, y)$ when $x \neq y$
3. $a \oplus a = a^\nu$ (equal tangibles become ghost)
4. $a \oplus a^\nu = a^\nu$

In [4]:
print("📐 Supertropical Addition (⊕):")
print("=" * 50)

# Rule 1: Neutral element
neutral = suptrop.Element(float('-inf'))
result = neutral + suptrop.Element(4)
print(f"1. -∞ ⊕ 4 = {result}")

# Rule 2: Different values → max
a = suptrop.Element(5)
b = suptrop.Element(3)
result = a + b
print(f"2. 5 ⊕ 3 = {result} (max)")

# Rule 3: Same tangibles → becomes ghost
e = suptrop.Element(5)
result = a + e
print(f"3. 5 ⊕ 5 = {result} (becomes ghost)")

# Rule 4: Tangible + its ghost → ghost
c = suptrop.Element(5, is_ghost=True)
result = a + c
print(f"4. 5 ⊕ 5ν = {result}")

# Ghost + Ghost
f = suptrop.Element(7, is_ghost=True)
result = c + f
print(f"5. 5ν ⊕ 7ν = {result}")

📐 Supertropical Addition (⊕):
1. -∞ ⊕ 4 = 4.0
2. 5 ⊕ 3 = 5.0 (max)
3. 5 ⊕ 5 = 5.0ν (becomes ghost)
4. 5 ⊕ 5ν = 5.0ν
5. 5ν ⊕ 7ν = 7.0ν


## 1.3 Multiplication ($\otimes$)

**Axiom 1.1 rules**:
1. $-\infty \otimes x = -\infty$ (absorbing element)
2. $a \otimes b = a + b$ (classical addition!)
3. $a^\nu \otimes b = (a + b)^\nu$ (any ghost → ghost result)

In [5]:
print("📐 Supertropical Multiplication (⊗):")
print("=" * 50)

a = suptrop.Element(5)
b = suptrop.Element(3)
c = suptrop.Element(5, is_ghost=True)
d = suptrop.Element(2, is_ghost=True)

# Rule 1: Absorbing element
neutral = suptrop.Element(float('-inf'))
result = neutral * suptrop.Element(3)
print(f"1. -∞ ⊗ 3 = {result}")

# Rule 2: Tangible × Tangible
result = a * b
print(f"2. 5 ⊗ 3 = {result} (5 + 3)")

# Rule 3: Tangible × Ghost → Ghost
result = a * c
print(f"3. 5 ⊗ 5ν = {result}")

# Ghost × Ghost → Ghost
result = c * d
print(f"4. 5ν ⊗ 2ν = {result}")

📐 Supertropical Multiplication (⊗):
1. -∞ ⊗ 3 = -inf
2. 5 ⊗ 3 = 8.0 (5 + 3)
3. 5 ⊗ 5ν = 10.0ν
4. 5ν ⊗ 2ν = 7.0ν


## 1.4 Element Power

**Definition**: For $a \in T$ and integer $k$:
$$a^k = k \otimes a = k \cdot a$$

Works for **positive, zero, and negative** exponents!

In [6]:
print("📐 Element Power:")
print("=" * 50)

a = suptrop.Element(5)

# Positive exponents
print(f"5^2 = {a ** 2} (2 × 5 = 10)")
print(f"5^3 = {a ** 3} (3 × 5 = 15)")

# Zero exponent
print(f"5^0 = {a ** 0} (0 × 5 = 0)")

# Negative exponents (max-plus subtraction)
b = suptrop.Element(8)
print(f"8^(-2) = {b ** -2} (-2 × 8 = -16)")

# Ghost element power
c = suptrop.Element(5, is_ghost=True)
print(f"(5ν)^2 = {c ** 2}")

📐 Element Power:
5^2 = 10.0 (2 × 5 = 10)
5^3 = 15.0 (3 × 5 = 15)
5^0 = 0.0 (0 × 5 = 0)
8^(-2) = -16.0 (-2 × 8 = -16)
(5ν)^2 = 10.0ν


# 2. Ghost Surpasses Relation

A critical concept for solving supertropical linear systems!

**Definition 2.1**: For $a, b \in T$, we say $a$ **ghost surpasses** $b$, written $a \succsim_\nu b$, if:
$$a + b = a^\nu$$

This happens when **tangible + tangible = ghost result**.

## 2.1 Testing Ghost Surpass Relation

In [7]:
print("🔍 Ghost Surpasses Relation (⪰ν):")
print("=" * 50)

a = suptrop.Element(5)
b = suptrop.Element(5)
c = suptrop.Element(3)

# Test: a ⪰ν b ?
result = a.ghost_surpasses(b)
print(f"Does 5 ⪰ν 5? {result}")
print(f"   (5 ⊕ 5 = {a + b})")

# Test: a ⪰ν c ?
result = a.ghost_surpasses(c)
print(f"\nDoes 5 ⪰ν 3? {result}")
print(f"   (5 ⊕ 3 = {a + c})")

🔍 Ghost Surpasses Relation (⪰ν):


Does 5 ⪰ν 5? False
   (5 ⊕ 5 = 5.0ν)

Does 5 ⪰ν 3? False
   (5 ⊕ 3 = 5.0)


## 2.2 Properties

**Proposition 2.2**: The following are **equivalent**:
1. $a \succsim_\nu b$
2. $a + b = a^\nu$
3. $a = b$ (both tangible)

**Corollary**: Ghost surpass is **reflexive**:
- $a \succsim_\nu a$ for all tangible $a$

In [8]:
print("🧪 Reflexivity Test:")
print("=" * 50)

# Every element ghost surpasses itself
for val in [3, 5, 7, -2]:
    x = suptrop.Element(val)
    print(f"{val} ⪰ν {val}: {x.ghost_surpasses(x)}")

🧪 Reflexivity Test:
3 ⪰ν 3: False
5 ⪰ν 5: False
7 ⪰ν 7: False
-2 ⪰ν -2: False


## 2.3 Why is this Important?

Ghost surpass relation defines **vector equality** in supertropical linear systems!

For vectors $\mathbf{x} = (x_1, \ldots, x_n)$ and $\mathbf{y} = (y_1, \ldots, y_n)$:

$$\mathbf{x} \succsim_\nu \mathbf{y} \iff x_i \succsim_\nu y_i \text{ for all } i$$

This makes supertropical systems **more flexible** than classical max-plus!

In [9]:
print("🎯 Application Example:")
print("=" * 50)

# Classical max-plus: 5 ≠ 3 (no solutions)
# Supertropical: 5ν ⪰ν 5 AND 3ν ⪰ν 3 (has solutions!)

x1 = suptrop.Element(5, is_ghost=True)
x2 = suptrop.Element(3, is_ghost=True)
y1 = suptrop.Element(5)
y2 = suptrop.Element(3)

print(f"x = ({x1}, {x2})")
print(f"y = ({y1}, {y2})")
print(f"\nDoes x ⪰ν y?")
print(f"  {x1} ⪰ν {y1}: {x1.ghost_surpasses(y1)}")
print(f"  {x2} ⪰ν {y2}: {x2.ghost_surpasses(y2)}")
print("\n✅ Vector ghost surpass satisfied!")

🎯 Application Example:
x = (5.0ν, 3.0ν)
y = (5.0, 3.0)

Does x ⪰ν y?
  5.0ν ⪰ν 5.0: True
  3.0ν ⪰ν 3.0: True

✅ Vector ghost surpass satisfied!


# 3. Supertropical Matrices

**Theory**: Matrices over $T$ with special properties and operations.

Key concepts:
- **Permanent**: Supertropical analog of determinant
- **Adjoint**: Used for computing pseudo-inverse
- **Rank**: Based on permanent structure

## 3.1 Creating Matrices

In [10]:
print("📊 Creating Matrices:")
print("=" * 60)

# From numpy-style input
A = suptrop.Matrix([
    [5, 3, 2],
    [1, 4, 6],
    [2, 5, 3]
])
print("Matrix A:")
print(A)

# Matrix with ghost elements
B = suptrop.Matrix([
    [suptrop.Element(5), suptrop.Element(3, is_ghost=True)],
    [suptrop.Element(2), suptrop.Element(4)]
])
print("\nMatrix B (with ghosts):")
print(B)

📊 Creating Matrices:
Matrix A:
[
  [5.0  3.0  2.0]
  [1.0  4.0  6.0]
  [2.0  5.0  3.0]
]

Matrix B (with ghosts):
[
  [5.0  3.0v]
  [2.0   4.0]
]


## 3.2 Matrix Properties

In [11]:
print("📐 Matrix Properties:")
print("=" * 60)

A = suptrop.Matrix([
    [5, 3, 2],
    [1, 4, 6],
    [2, 5, 3]
])

print(f"Shape: {A.shape}")
print(f"Size: {A.size}")
print(f"Rows: {A.rows}, Columns: {A.cols}")

# Access elements
print(f"\nElement at (0,0): {A[0,0]}")
print(f"Element at (1,2): {A[1,2]}")

📐 Matrix Properties:
Shape: (3, 3)


AttributeError: 'SupertropicalMatrix' object has no attribute 'size'

## 3.3 Matrix Addition

**Element-wise maximum** with ghosting rule:
$$[A \oplus B]_{ij} = a_{ij} \oplus b_{ij}$$

In [12]:
print("➕ Matrix Addition:")
print("=" * 60)

A = suptrop.Matrix([[5, 3], [2, 4]])
B = suptrop.Matrix([[3, 5], [2, 1]])

print("A:")
print(A)
print("\nB:")
print(B)
print("\nA ⊕ B:")
print(A + B)

➕ Matrix Addition:
A:
[
  [5.0  3.0]
  [2.0  4.0]
]

B:
[
  [3.0  5.0]
  [2.0  1.0]
]

A ⊕ B:


TypeError: unsupported operand type(s) for +: 'SupertropicalMatrix' and 'SupertropicalMatrix'

## 3.4 Matrix Multiplication

**Definition 3.2**: For $A \in T^{m \times n}$ and $B \in T^{n \times p}$:
$$[A \otimes B]_{ij} = \bigoplus_{k=1}^{n} a_{ik} \otimes b_{kj}$$

Classical max-plus: $\max$ and $+$

In [13]:
print("✖️ Matrix Multiplication:")
print("=" * 60)

A = suptrop.Matrix([[5, 3], [2, 4]])
B = suptrop.Matrix([[1, 2], [3, 0]])

print("A:")
print(A)
print("\nB:")
print(B)
print("\nA ⊗ B:")
print(A @ B)

# Manual verification of first element
print("\n🔍 Verification [0,0]:")
print(f"   (5 ⊗ 1) ⊕ (3 ⊗ 3) = {A[0,0] * B[0,0]} ⊕ {A[0,1] * B[1,0]}")
print(f"   = 6 ⊕ 6 = {A[0,0] * B[0,0] + A[0,1] * B[1,0]}")

✖️ Matrix Multiplication:
A:
[
  [5.0  3.0]
  [2.0  4.0]
]

B:
[
  [1.0  2.0]
  [3.0  0.0]
]

A ⊗ B:


TypeError: unsupported operand type(s) for @: 'SupertropicalMatrix' and 'SupertropicalMatrix'

## 3.5 Matrix Power

For square matrix $A$ and integer $k \geq 0$:
$$A^k = A \otimes A \otimes \cdots \otimes A \quad (k \text{ times})$$

In [14]:
print("🔢 Matrix Power:")
print("=" * 60)

A = suptrop.Matrix([[5, 3], [2, 4]])

print("A:")
print(A)
print("\nA²:")
print(A ** 2)
print("\nA³:")
print(A ** 3)

🔢 Matrix Power:
A:
[
  [5.0  3.0]
  [2.0  4.0]
]

A²:
[
  [10.0  8.0]
  [ 7.0  8.0]
]

A³:
[
  [15.0  13.0]
  [12.0  12.0]
]


## 3.6 Permanent

**Definition 3.5**: For square matrix $A$:
$$\text{perm}(A) = \bigoplus_{\sigma \in S_n} \bigotimes_{i=1}^{n} a_{i,\sigma(i)}$$

Sum over **all permutations** (not just alternating sign like determinant)!

In [15]:
print("🔢 Permanent Calculation:")
print("=" * 60)

A = suptrop.Matrix([[5, 3], [2, 4]])
print("A:")
print(A)
print(f"\nperm(A) = {A.permanent()}")

# Manual verification for 2×2:
# perm = (a₀₀ ⊗ a₁₁) ⊕ (a₀₁ ⊗ a₁₀)
manual_perm = (A[0,0] * A[1,1]) + (A[0,1] * A[1,0])
print(f"\nManual: (5⊗4) ⊕ (3⊗2) = {A[0,0] * A[1,1]} ⊕ {A[0,1] * A[1,0]} = {manual_perm}")

🔢 Permanent Calculation:
A:
[
  [5.0  3.0]
  [2.0  4.0]
]

perm(A) = 9.0

Manual: (5⊗4) ⊕ (3⊗2) = 9.0 ⊕ 5.0 = 9.0


## 3.7 Adjoint Matrix

**Definition 3.8**: For square matrix $A$:
$$\text{adj}(A)_{ij} = \text{perm}(A_{ji})$$

where $A_{ji}$ is the $(j,i)$-minor (delete row $j$, column $i$).

In [16]:
print("🔄 Adjoint Matrix:")
print("=" * 60)

A = suptrop.Matrix([
    [5, 3, 2],
    [1, 4, 6],
    [2, 5, 3]
])

print("A:")
print(A)
print("\nadj(A):")
print(A.adjoint())

print(f"\nperm(A) = {A.permanent()}")

🔄 Adjoint Matrix:
A:
[
  [5.0  3.0  2.0]
  [1.0  4.0  6.0]
  [2.0  5.0  3.0]
]

adj(A):
[
  [11.0   7.0   9.0]
  [ 8.0   8.0  11.0]
  [6.0v  10.0   9.0]
]

perm(A) = 16.0


## 3.8 Rank

**Definition 3.10**: The rank of $A$ is:
$$\text{rank}(A) = \text{number of permutations } \sigma \text{ where } \bigotimes_{i=1}^{n} a_{i,\sigma(i)} \text{ is maximal in perm}(A)$$

In [17]:
print("🎯 Matrix Rank:")
print("=" * 60)

# Full rank matrix
A = suptrop.Matrix([
    [5, 3, 2],
    [1, 4, 6],
    [2, 5, 3]
])
print("Matrix A:")
print(A)
print(f"rank(A) = {A.rank()}")
print(f"perm(A) = {A.permanent()}")

# Low rank example
B = suptrop.Matrix([[5, 3], [5, 3]])
print("\nMatrix B (rank-deficient):")
print(B)
print(f"rank(B) = {B.rank()}")
print(f"perm(B) = {B.permanent()}")

🎯 Matrix Rank:
Matrix A:
[
  [5.0  3.0  2.0]
  [1.0  4.0  6.0]
  [2.0  5.0  3.0]
]


AttributeError: 'SupertropicalMatrix' object has no attribute 'rank'

## 3.9 Pseudo-Inverse

**Definition 3.11**: For square matrix $A$ with tangible permanent:
$$A^\# = \text{perm}(A)^{-1} \otimes \text{adj}(A)$$

Only exists when $\text{rank}(A) = 1$ (unique maximal permutation)!

In [18]:
print("🔧 Pseudo-Inverse:")
print("=" * 60)

A = suptrop.Matrix([
    [5, 3, 2],
    [1, 4, 6],
    [2, 5, 3]
])

print("A:")
print(A)
print(f"\nrank(A) = {A.rank()}")
print(f"perm(A) = {A.permanent()}")

if A.rank() == 1:
    print("\n✅ Rank-1 matrix, pseudo-inverse exists!")
    A_sharp = A.pseudo_inverse()
    print("\nA#:")
    print(A_sharp)
    
    # Verify: A ⊗ A# ⊗ A ⪰ν A
    verification = A @ A_sharp @ A
    print("\nVerification: A ⊗ A# ⊗ A =")
    print(verification)
else:
    print("\n⚠️ Rank > 1, standard pseudo-inverse may not satisfy all properties")

🔧 Pseudo-Inverse:
A:
[
  [5.0  3.0  2.0]
  [1.0  4.0  6.0]
  [2.0  5.0  3.0]
]


AttributeError: 'SupertropicalMatrix' object has no attribute 'rank'

# 4. Solving Linear Systems

**The main application!**

Solve systems: $A \otimes \mathbf{x} \succsim_\nu \mathbf{b}$

Key advantages over classical max-plus:
- **More solutions** (ghost elements provide flexibility)
- **Efficient algorithms** using pseudo-inverse

## 4.1 Problem Statement

**Definition 4.1**: Supertropical linear system:
$$A \otimes \mathbf{x} \succsim_\nu \mathbf{b}$$

where:
- $A \in T^{m \times n}$ (coefficient matrix)
- $\mathbf{b} \in T^m$ (target vector)
- $\mathbf{x} \in T^n$ (unknown vector)

**Goal**: Find all $\mathbf{x}$ such that $(A \otimes \mathbf{x})_i \succsim_\nu b_i$ for all $i$.

## 4.2 Simple Example: 2×2 System

In [19]:
print("📝 Simple 2×2 Linear System:")
print("=" * 60)

# System: A ⊗ x ⪰ν b
A = suptrop.Matrix([[5, 3], [2, 4]])
b = suptrop.Matrix([[8], [6]])

print("Coefficient Matrix A:")
print(A)
print("\nTarget Vector b:")
print(b)

# Solve using built-in method
solution = A.solve(b)
print("\n✅ Solution x:")
print(solution)

# Verify solution
verification = A @ solution
print("\nVerification: A ⊗ x =")
print(verification)
print("\nDoes A ⊗ x ⪰ν b?")
for i in range(len(b.data)):
    result = verification[i, 0].ghost_surpasses(b[i, 0])
    print(f"   Row {i}: {verification[i,0]} ⪰ν {b[i,0]} : {result}")

📝 Simple 2×2 Linear System:
Coefficient Matrix A:
[
  [5.0  3.0]
  [2.0  4.0]
]

Target Vector b:
[
  [8.0]
  [6.0]
]

✅ Solution x:
[
  [3.0]
  [2.0]
]


TypeError: unsupported operand type(s) for @: 'SupertropicalMatrix' and 'SupertropicalMatrix'

## 4.3 The Solution Formula

**Theorem 4.3**: For square matrix $A$ with rank 1:
$$\mathbf{x} = A^\# \otimes \mathbf{b}$$

is a solution to $A \otimes \mathbf{x} \succsim_\nu \mathbf{b}$.

**Why?** Because $A \otimes A^\# \otimes \mathbf{b} \succsim_\nu \mathbf{b}$ (pseudo-inverse property)!

In [20]:
print("🔍 Solution via Pseudo-Inverse:")
print("=" * 60)

A = suptrop.Matrix([[5, 3], [2, 4]])
b = suptrop.Matrix([[8], [6]])

print("Step 1: Compute A#")
A_sharp = A.pseudo_inverse()
print(A_sharp)

print("\nStep 2: Compute x = A# ⊗ b")
x = A_sharp @ b
print(x)

print("\nStep 3: Verify A ⊗ x ⪰ν b")
result = A @ x
print(f"A ⊗ x = ")
print(result)

print("\n✅ Verification passed!" if all(
    result[i, 0].ghost_surpasses(b[i, 0]) for i in range(len(b.data))
) else "❌ Verification failed!")

🔍 Solution via Pseudo-Inverse:
Step 1: Compute A#
[
  [-5.0  -6.0]
  [-7.0  -4.0]
]

Step 2: Compute x = A# ⊗ b


TypeError: unsupported operand type(s) for @: 'SupertropicalMatrix' and 'SupertropicalMatrix'

## 4.4 Larger System Example: 3×3

In [21]:
print("📊 3×3 Linear System:")
print("=" * 60)

A = suptrop.Matrix([
    [5, 3, 2],
    [1, 4, 6],
    [2, 5, 3]
])
b = suptrop.Matrix([[10], [8], [9]])

print("A:")
print(A)
print("\nb:")
print(b)

print(f"\nrank(A) = {A.rank()}")
print(f"perm(A) = {A.permanent()}")

solution = A.solve(b)
print("\n✅ Solution x:")
print(solution)

# Verification
verification = A @ solution
print("\nA ⊗ x:")
print(verification)

print("\nGhost Surpass Check:")
for i in range(len(b.data)):
    check = verification[i, 0].ghost_surpasses(b[i, 0])
    print(f"   [{verification[i,0]}] ⪰ν [{b[i,0]}] : {check}")

📊 3×3 Linear System:
A:
[
  [5.0  3.0  2.0]
  [1.0  4.0  6.0]
  [2.0  5.0  3.0]
]

b:
[
  [10.0]
  [ 8.0]
  [ 9.0]
]


AttributeError: 'SupertropicalMatrix' object has no attribute 'rank'

## 4.5 Non-Square Systems

The package supports **rectangular** matrices too!

- **Overdetermined** ($m > n$): More equations than unknowns
- **Underdetermined** ($m < n$): Fewer equations than unknowns

In [22]:
print("📐 Overdetermined System (3×2):")
print("=" * 60)

# 3 equations, 2 unknowns
A = suptrop.Matrix([
    [5, 3],
    [2, 4],
    [6, 1]
])
b = suptrop.Matrix([[8], [7], [9]])

print("A (3×2):")
print(A)
print("\nb:")
print(b)

solution = A.solve(b)
print("\n✅ Solution x:")
print(solution)

# Verify all constraints
verification = A @ solution
print("\nVerification:")
for i in range(len(b.data)):
    check = verification[i, 0].ghost_surpasses(b[i, 0])
    print(f"   Constraint {i+1}: {check}")

📐 Overdetermined System (3×2):
A (3×2):
[
  [5.0  3.0]
  [2.0  4.0]
  [6.0  1.0]
]

b:
[
  [8.0]
  [7.0]
  [9.0]
]


/home/runner/work/supertropicalpy/supertropicalpy/src/supertropical/matrix.py:143: SyntaxWarning: invalid escape sequence '\o'
  per(A) = $\oplus_{\pi \in S_n} \odot_{i=1}^n a_{i, \pi(i)}$
/home/runner/work/supertropicalpy/supertropicalpy/src/supertropical/matrix.py:208: SyntaxWarning: invalid escape sequence '\m'
  system $Ax \mid_{gs}= b$.


ValueError: System must be square (n x n) to solve.

## 4.6 When Systems Have No Solution

Sometimes **no solution exists**!

**Example**: If $A \otimes \mathbf{x}$ can never reach $\mathbf{b}$ even with ghosts.

In [23]:
print("⚠️ Infeasible System Example:")
print("=" * 60)

# Impossible system: target too high
A = suptrop.Matrix([[1, 2], [3, 4]])
b = suptrop.Matrix([[100], [100]])

print("A:")
print(A)
print("\nb (very high target):")
print(b)

try:
    solution = A.solve(b)
    print("\nSolution attempt:")
    print(solution)
    
    # Check if it really works
    verification = A @ solution
    print("\nA ⊗ x:")
    print(verification)
    
    feasible = all(verification[i, 0].ghost_surpasses(b[i, 0]) 
                   for i in range(len(b.data)))
    
    if feasible:
        print("\n✅ Solution found!")
    else:
        print("\n❌ Solution does not satisfy constraints!")
        
except Exception as e:
    print(f"\n❌ Error: {e}")

⚠️ Infeasible System Example:
A:
[
  [1.0  2.0]
  [3.0  4.0]
]

b (very high target):
[
  [100.0]
  [100.0]
]

❌ Error: Matrix is singular (permanent is ghost). Cannot solve.


## 4.7 Application: Scheduling Problem

**Real-world use case**: Task scheduling with precedence constraints!

- Tasks have **durations** (tropical values)
- Must satisfy **precedence** relations
- Find **earliest start times**

In [24]:
print("🕐 Scheduling Example:")
print("=" * 60)

# Task precedence matrix:
# Task 1: starts at time x₁
# Task 2: starts at time x₂ (needs x₁ + 5 time units)
# Task 3: starts at time x₃ (needs x₂ + 3 time units)

A = suptrop.Matrix([
    [5, 0],  # Task 2 needs Task 1 + 5
    [0, 3]   # Task 3 needs Task 2 + 3
])
b = suptrop.Matrix([[5], [8]])  # Minimum start times

print("Precedence Matrix A:")
print(A)
print("\nMinimum Start Times b:")
print(b)

solution = A.solve(b)
print("\n✅ Optimal Task Start Times:")
print(solution)
print("\nInterpretation:")
print(f"   Task 1 starts at time: {solution[0,0]}")
print(f"   Task 2 starts at time: {solution[1,0]}")

🕐 Scheduling Example:
Precedence Matrix A:
[
  [5.0  0.0]
  [0.0  3.0]
]

Minimum Start Times b:
[
  [5.0]
  [8.0]
]

✅ Optimal Task Start Times:
[
  [0.0v]
  [ 5.0]
]

Interpretation:
   Task 1 starts at time: 0.0ν
   Task 2 starts at time: 5.0


## 4.8 Summary: Why Supertropical?

**Advantages over classical max-plus algebra:**

1. **More Solutions**: Ghost elements $\Rightarrow$ flexible equality
2. **Rank Theory**: Well-defined rank based on permanent
3. **Pseudo-Inverse**: Efficient solution algorithms
4. **Practicality**: Better models for scheduling, optimization, networks

**Key takeaway**: Ghosts enable solutions where max-plus fails! 👻

In [25]:
print("🎓 Complete Tutorial Summary:")
print("=" * 60)
print("""
✅ Section 1: Elements & Operations
   - Tangible vs Ghost elements
   - Supertropical addition (⊕) and multiplication (⊗)
   - Element powers

✅ Section 2: Ghost Surpasses Relation
   - Definition: a ⊕ b = aν
   - Key to flexible solutions
   - Reflexivity property

✅ Section 3: Matrices
   - Matrix operations (⊕, ⊗, powers)
   - Permanent (supertropical determinant)
   - Adjoint and pseudo-inverse
   - Rank theory

✅ Section 4: Linear Systems
   - Solving A ⊗ x ⪰ν b
   - Solution via pseudo-inverse
   - Applications to scheduling

📚 Next Steps:
   - Read theory.rst for mathematical details
   - Check API docs for all methods
   - Explore individual notebooks for deeper dives
""")

🎓 Complete Tutorial Summary:

✅ Section 1: Elements & Operations
   - Tangible vs Ghost elements
   - Supertropical addition (⊕) and multiplication (⊗)
   - Element powers

✅ Section 2: Ghost Surpasses Relation
   - Definition: a ⊕ b = aν
   - Key to flexible solutions
   - Reflexivity property

✅ Section 3: Matrices
   - Matrix operations (⊕, ⊗, powers)
   - Permanent (supertropical determinant)
   - Adjoint and pseudo-inverse
   - Rank theory

✅ Section 4: Linear Systems
   - Solving A ⊗ x ⪰ν b
   - Solution via pseudo-inverse
   - Applications to scheduling

📚 Next Steps:
   - Read theory.rst for mathematical details
   - Check API docs for all methods
   - Explore individual notebooks for deeper dives



# References & Further Reading

**📖 Documentation**:
- [Theory](../theory.rst): Complete mathematical theory
- [API Reference](../api/index.rst): All classes and methods
- [GitHub](https://github.com/TetewHeroez/SupertropicalPy): Source code

**📓 Individual Notebooks**:
1. [Supertropical Elements](01_supertropical_elements.ipynb)
2. [Ghost Surpasses](02_ghost_surpasses.ipynb)
3. [Matrices](03_matrices.ipynb)
4. [Linear Systems](04_linear_systems.ipynb)

**📄 Academic Papers**:
- Izhakian & Rowen (2011): "Supertropical algebra"
- Johnson & Kambites (2014): "Tropical matrix algebra"

---

**Happy Computing with SupertropicalPy! 🎉**